### ISSUE TITLE
Event is triggered one page click

### ISSUE THREAD

**Issue by RyanHelmn** [easepick/easepick#129]
**Describe the bug**
This may or may not be a bug, but it'd be great to understand a workaround. I've got a unique use-case, where I need dates highlighted depending on a status returned from an API.

using the `picker.on("view")` event, I'm looping through all of the present dates, making the necessary API call and applying a css class to add a background colour to said date depending on said status.
![image](https://user-images.githubusercontent.com/44208607/189157769-f52cb505-2e01-4f3c-a1eb-3dec9b834802.png)

However, if I click anywhere within the page, the `picker.on("view")` event is triggered again. Is this intentional? The API requests need to be made on first load and on month change.

**To Reproduce**
1. Setup a picker
2. initialise the `picker.on("view")` event and do a console.log
3. Click anywhere outside of the calendar, in the page, the console.log will be triggered again

**Expected behavior**
The `view` event makes it sound like it's triggered when the calendar is viewed

**Code Playground**

**Additional context**
As I mentioned before, it may or may not be a bug, or I may be trying to apply the use-case incorrectly, but it'd be great if anyone could point me in the right direction.

**Comment by arwinvdv** [comment]
This is because of the hidePicker function (to close the picker). We have the same issue with en picker inline, so I created an pull request (https://github.com/easepick/easepick/pull/163) to disable the hidePicker function when inline is enabled, because it is not necessary.
