### ISSUE TITLE
Featured requests - Adding new option to allow time picker instead of date

### ISSUE THREAD

**Issue by choijun** [easepick/easepick#142]
Hi guys,

First of all thanks for your great work, this is awesome package :100: :100: . I think it would be great if you add a feature that allows you to select only the time picker instead of the date, it will help a lot of people ( including me of course  :pray:).

Looking forward to your response .

Thanks & Regards,
Duy.

**Comment by sts-ryan-holton** [comment]
@choijun Not sure the project is being maintained, setting time doesn't currently work as described [here](https://github.com/easepick/easepick/issues/80)

**Comment by choijun** [comment]
Hi @sts-ryan-holton ,

Thanks for letting me know, I found another library and hope it helps you in the future too https://github.com/nhn/tui.time-picker .

**Comment by wakirin** [comment]
not planned at the moment
