### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by sts-ryan-holton** [easepick/easepick#144]
Hi 👋 

I'm currently using this plugin in one of my projects as I really like the UI and general theme. I'm using a combination of plugins, in particular the Range and Time plugin, both of which have several [issues](https://github.com/easepick/easepick/issues?q=is%3Aopen+is%3Aissue+label%3Atime-plugin) floating around on Github with little to no support.

In addition, the last active change on this project was many months ago.

Is this project still being maintained?

**Comment by wakirin** [comment]
No time for this project.
If some problems prevent you from continuing to work with this library and you cannot fix it, then I think it's better to choose some other library.

**Comment by jorgefelico** [comment]
@wakirin Would you be open to letting the GH community make updates/fixes and merging the PRs? At least assigning someone else that might have time to manage the repo with you.

**Comment by wakirin** [comment]
@jorgefelico How do you suggest to do it ? I would not like to give permission to someone who will merge any created PR. I have some vision of future versions, but I can't implement it at the moment due to being busy.

**Comment by mikekok** [comment]
> No time for this project. If some problems prevent you from continuing to work with this library and you cannot fix it, then I think it's better to choose some other library.

Any alternatives you'd recommend?

**Comment by sandstrom** [comment]
I like easepick, I think it's great!

But for those evaluating other options, have a look at https://github.com/t1m0n/air-datepicker

**Comment by mikekok** [comment]
> I like easepick, I think it's great!
> 
> But for those evaluating other options, have a look at https://github.com/t1m0n/air-datepicker

That one seems promising but unfortunately is not as mature as easepick yet.

First thing I noticed is that it's missing the ability to lock dates that are unavailable.
