### ISSUE TITLE
Repick (from range plugin) does not seem to work with inline 

### ISSUE THREAD

**Issue by PaperbagLife** [easepick/easepick#145]
**Describe the bug**
Repick option with range plugin does not work with inline. When inline is on, clicking the end input box does not behave as expected. It behaves as if the user is picking from the beginning. (ie. you have to click twice, choosing the start time again as well)

**To Reproduce**
1. Go to https://easepick.com/configurator/
2. Enable range plugin and turn on element end and repick
3. Enable inline from core
4. Pick a date, and repick by clicking on the element end and pick a date

**Expected behavior**
For the end date to be set to the date picked, and the start date remain unchanged

**Comment by wakirin** [comment]
repick only works with fields and doesn't support inline mode.
the configurator needs to be updated to disallow select repick option when inline mode is enabled.
