### ISSUE TITLE
Format causing dates to incorrectly become locked

### ISSUE THREAD

**Issue by chrisannetts** [easepick/easepick#150]
https://jsfiddle.net/q4ae8d0v/3/

When I change the default format, all but the current date incorrectly become disabled/locked. When I remove the format, the issue resolves. Interestingly, when I remove the maxDate from the LockPlugin, this also solved the issue.

What's really throwing me is that when I use the [configurator](https://easepick.com/configurator/) to produce the desired output, it works exactly as expected.

**Comment by wakirin** [comment]
look at the docs:
> The maximum/latest date that can be selected.
> Date Object or Unix Timestamp (with milliseconds) or ISO String.
> **When a date is provided as a string, it must be equal to the format option.**

in your case it should be `"30 Mar 2024"`
