### ISSUE TITLE
Two window picker inits with disabled future dates

### ISSUE THREAD

**Issue by cjayyy** [easepick/easepick#17]
**Describe the bug**
When having more than 1 calendar window, and set up `maxDate` to past/present, picker populates with wrong options (future disabled month).

**To Reproduce**
1. Init picker with following options:
```js
{
   calendars: 2,
   plugins: [LockPlugin],
   LockPlugin: {
      maxDate: new DateTime()
   }
}
```
3. Open picker 
4. See unusable second window with options of future (disabled) date

**Expected behavior**
Picker should initialize with correct (usable) options.

**Additional context**
I does fix itself when switching to past month - it's not possible to go back to the future. 

https://user-images.githubusercontent.com/14090214/161110679-fd019022-b227-4f0d-bd99-96a30786c4ae.mov

**Comment by wakirin** [comment]
> I does fix itself when switching to past month - it's not possible to go back to the future.

Why should it be possible? You are setting `maxDate` to the current date, so dates greater than `maxDate` will not be available.
You can check this case tomorrow (April 1st) and you will see that the faucet will start from April and the next month will be unavailable too.
What do you expected to see when set `maxDate` to the current date ?

**Comment by cjayyy** [comment]
Sorry I probably didn't express correctly.

The disabled future is not available - I can't go to next month when max date is today - and that is correct. The bug is that it is like this after I change month one back. On video you can see it started with disabled April on bottom (wrong), but after I clicked to the previous month I wasn't able to click to the next month - April - again (correct).

**Comment by cjayyy** [comment]
> What do you expected to see when set 'maxDate' to the current date ?

Window 1: previous month,
Window 2: current month

**Comment by wakirin** [comment]
> Window 1: previous month,
> Window 2: current month

Yes, it makes sense. I will include a fix in the next release. 
Thanks for suggestion.

**Comment by cjayyy** [comment]
Thank you! :)
