### ISSUE TITLE
Intl and Temporal

### ISSUE THREAD

**Issue by sandstrom** [easepick/easepick#180]
Thanks for an awesome project! 🏅 

I think for any date picker that want to make maintenance somewhat easy, it should rely on the browser for localisation.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat (and others in the Intl group)

It should also be built on Temporal, the upcoming replacement for `Date` in JS:

https://github.com/js-temporal/temporal-polyfill

Just wanted to suggest this. Feel free to close this issue.

**Comment by wakirin** [comment]
Thanks for suggestions, I like the idea with Temporal.
