### ISSUE TITLE
If input placed in label, close methods don't work

### ISSUE THREAD

**Issue by evtihii** [easepick/easepick#185]
**Describe the bug**
I've spent a few ours to understand why filed stopped closing)

**To Reproduce**
1. Create label
2. Place input into label
3. Try to choose any date

**Expected behavior**
Calendar has been closed

**Code Playground**
https://codepen.io/evtihii/pen/VwEWJJx

**Comment by wakirin** [comment]
nice catch, for the moment you can add this:

```js
picker.on('click', (e) => {
  e.preventDefault();
});
```

I will add a fix to the future versions.
