### ISSUE TITLE
no auto populate, plus Range/Time plugins, startDate: endDate: do not function as documented, generate 62 clone complaints in console

### ISSUE THREAD

**Issue by h3rb** [easepick/easepick#3]
**Describe the bug**

Couple of issues here, found at the same time.

1) "startDate" and and "endDate" RangePlugin options do not seem to have the same flexibility as "setStartDate" and "setStartTime", and I was unable to get them to work because it complains that ".clone" is not a valid method, even if I put new Date(...) instead of  string, or a numeric timestamp generated with Math.floor(new Date().getTime()/1000)

2) RangePlugin does not accept value for time (hours/minutes/seconds/millis) when provided via the methods setStartDate and setStartTime, making it impossible to set a default for the TimePlugin

3) TimePlugin has no way to set starting values, so if I wanted the default to be 0:0:00 (midnight) to 23:59:59 no way to do this.

4) Using format: option with H:m:s made the resulting input time string all screwy, as the TimePlugin just sticks its time value right before the date no matter what.

5) You can't stick a value inside the input tag and have it automatically populate the range and time values when the picker is created.

6) Usability with auto-apply and TimePlugin: When picking a date that is the same date for the range, it closes the window before you can select the time.  Ie  "March 21 2022 - March 21 2022" ... There is no way to create a "close button" so you have no way not to "auto apply" your changes except using "Apply" "Cancel".  and other is no easy way to change the text of these buttons, ie "Check" "X"

7) I need a way to set the divider / seperator.  Other datepickers use ~ .. it would be nice to change it from '-' to '~'

**To Reproduce**

```js
	 this.created_picker = new easepick.create({
        element: document.getElementById('manager-search-date-created'),
		plugins: ['RangePlugin', 'TimePlugin'],
        RangePlugin: {
          tooltipNumber(num) {
            return num - 1;
          },
          locale: {
            one: 'day',
            other: 'days',
          },
          startDate: new Date(),
          endDate: 'March 23, 1:35pm'
        },
		TimePlugin: {
			seconds: true,
			append: 'start',
			stepMinutes: 1,
			stepSeconds: 1
		},
        css: [
          'app/js/lib/easepick/easepick.css',
        ],
      });
```

**Expected behavior**

1) There was no way I could use these options.  I was forced to use methods setStartDate and setEndDate

2) I had created specific strings and used `new Date(...)` but it didn't take into account the time values, even though the time plugin was activated.

3) I need a way to set the start Hour/ Minute/Second on the "End time"

4) This needs some refactoring.  I cannot figure out how to get the date/time format to change when using the TimePlugin. Setting the "format:" option to "MMMM DD YYYYY HH:mm:ss" for example (matching a default Javascript date format) caused it to display as `0:00 March 22 2022 0:00:00 - 0:07 March 22 2022 07:55:22`

5) This seemed like a no-brainer, but I was surprised it didn't work.  I tried generating the string but it didn't just work magically, so I've had to dig into these other features.  It would have been easiest if I could have just provided it with a value and had it populate.  Normally when you are dealing with a date picker, you have some way of accurately setting the date, and its usually just by a string -- because you've retrieved that data from a database, most likely

6) & 7) Very confusing.  Not enough features to customize the text or buttons.

I picked this plugin over "daterangepicker" and "tempus-dominus" because it displayed correctly out of the box in a WinBoxjs (https://github.com/h3rb/winbox) window.  I'd love it if it had some more features that made using it easier/possible.  As it stands now the functionality for picking date ranges with time is a bit crippled.

**Addendum**

Using moment.js, you can generate the values I was testing with this way:
```js
	 var defaultDateTime = '00:00 '+now.getFullYear()+'-'+(now.getMonth()+1)+'-'+now.getDate()+' - 23:59 '+now.getFullYear()+'-'+(now.getMonth()+1)+'-'+now.getDate();
	 var startTime = moment(0,"HH").format('MMMM D, YYYY H:mm:ss');
	 var endTime = moment().add(1,"days").format('MMMM D, YYYY H:mm:ss'); // not supported by easepick :( moment({hour: 23, minute: 59, seconds: 59}).endOf('data').format('MMMM D, YYYY H:mm:ss');
```

**Comment by wakirin** [comment]
At the moment I can only speak about 6., 7. 
https://jsfiddle.net/waki/qd4chsfv/

I will consider other points and prepare an update if necessary.
Thanks for the detailed issue.

**Comment by wakirin** [comment]
I prepared a beta version (1.0.2-beta.0)
Now auto populate working, you need to provide the same format as you have in `format` option.
Added 3 methods: `setTime` (for single date) and `setStartTime`, `setEndTime` (for date range).
Removed `format` , `append` options from @easepick/time-plugin.

Here is a demo: https://jsfiddle.net/waki/104p2uhL/

**Comment by 1ucay** [comment]
Can you plese add method to range plugin? setMinDate etc? Thank you.
