### ISSUE TITLE
The first time the date picker is open it is misplaced.

### ISSUE THREAD

**Issue by titosuarezb** [easepick/easepick#32]
**Describe the bug**
The first time the date picker is open it is misplaced, after the first time it is positioned correctly.

**To Reproduce**
1. Go to https://easepick.com/configurator
2. Click on the date picker input
3. The date picker shows in the the center of the input.
4. Close the date picker.
5. Click on the date picker input.
6. Now the date picker is in another position.

**Expected behavior**
The date picker should show in a consistent position.

**Code Playground**
https://easepick.com/configurator

**Comment by wakirin** [comment]
related to discussion #29 

fix will be in the next release.
