### ISSUE TITLE
Custom Preset plugin

### ISSUE THREAD

**Issue by wakirin** [easepick/easepick#62]
### Discussed in https://github.com/easepick/easepick/discussions/61

<div type='discussions-op-text'>

<sup>Originally posted by **pallardino** May 14, 2022</sup>
An other question for customising preset-plugin. 

- First, I have tried to customise labels to put it in French. According to the documentation I passed a list of string, but unfortunately I got the following error from my js console : 
`TypeError: this.options.customLabels.forEach is not a function. (In 'this.options.customLabels.forEach(((t,e)=>{this.options.customPreset[t]=s[e]}))', 'this.options.customLabels.forEach' is undefined)`
- Second, I don't really understand how I can define your own ranges. According to the documentation I have to pass an object, but which object ? For exemple, I would like delete all predefined range and create a custom range for a year. 

<img width="446" alt="Capture d’écran 2022-05-13 à 10 21 44 PM" src="https://user-images.githubusercontent.com/39769580/168385220-473deee9-6d0c-41dd-ba83-1bb29cd27d1a.png">

Thanks in advance
 </div>

**Comment by CosmoFox** [comment]
Interested in custom ranges too. Waiting for author of this amazing project
