### ISSUE TITLE
Disabled "This Month" bug

### ISSUE THREAD

**Issue by CosmoFox** [easepick/easepick#64]
**Describe the bug**
When use lock-plugin (with max date = today) + preset-plugin button "this month" is disabled.

**Expected behavior**
If there is a limit (max date) - button "this month" must select from 1st day of this month to max date (today)

**Screenshot**
![image](https://user-images.githubusercontent.com/9054349/168960096-90e3503d-0476-4abb-b7ec-a5df91f463b8.png)

**Comment by wakirin** [comment]
I think we can't consider this a bug.
This block depends on the provided preset ranges.
I will not make the picker change the preset range itself.

If you really need this feature, you can do something like this:
https://jsfiddle.net/waki/56ae3jky/
