### ISSUE TITLE
can't initialize a picker, clone is not a function

### ISSUE THREAD

**Issue by andresContreras9996** [easepick/easepick#69]
**Describe the bug**
I'm trying to use the library in a stenciljs project, I installed the bundle of npm but when I create a new instance this throw an error

**To Reproduce**
![image](https://user-images.githubusercontent.com/79164727/169920029-b88c65e2-522f-462c-980a-8583d64cc7b3.png)
![image](https://user-images.githubusercontent.com/79164727/169920061-2da24e10-8992-4d9a-8276-3ec1e1d6ae35.png)

Aditional context: Im also working this on storybook

**Comment by wakirin** [comment]
Could you create minimal, reproducible example ? (new repo or any code playground)

**Comment by wakirin** [comment]
Please provide a link to the code playground (eg.: jsfiddle, stackblitz) with this problem to re-open the issue.
