### ISSUE TITLE
CSS via node_modules or local folder

### ISSUE THREAD

**Issue by maicolbruski** [easepick/easepick#71]
Hi,

I am trying to use the `easepick` into my component using VUE3, but when change de css (param) to de autoimport, doesn't work for me, always need an external css url into config?

It's possible?

![image](https://user-images.githubusercontent.com/3951164/171636604-ecfc8be6-b67e-434b-8cc4-109bcdd2c386.png)
--
![image](https://user-images.githubusercontent.com/3951164/171636200-dc47280c-a3e2-41f3-a0b2-aabd82d4204a.png)
--
![image](https://user-images.githubusercontent.com/3951164/171635859-a8fb0975-3496-4f10-a3ef-cfb85bd71a73.png)

**Comment by wakirin** [comment]
Yes, it's because of the ShadowDOM.
You can find some solutions for webpack in the discussions: https://github.com/easepick/easepick/discussions?discussions_q=webpack

**Comment by VladyslavL** [comment]
@Grawl you saved my day! Thanks you!!!
